services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=dev
    restart: unless-stopped